import { AnimatePresence, motion, useMotionValue } from 'framer-motion';
import { useEffect, useMemo, useRef, useState } from 'react';
import { cats, projects, order, catMap, imgFor, aboutData } from './data.js';

const dropEase=[.34,1.56,.64,1];
const coverEase=[.83,0,.17,1];
const coverT={duration:.72,ease:coverEase};
const routeBg={home:'#FFFFFF',projects:'#307FFF',about:'#F6F5EE'};
const Nav=({route,go})=>
  <nav className={`nav ${route==='projects'?'nav-projects':route==='about'?'nav-about':''}`}>
    <button onClick={()=>go('home',true)}>HOME</button>
    <button onClick={()=>go('projects',true)}>PROJECTS</button>
    <button onClick={()=>go('about',true)}>ABOUT</button>
  </nav>;
const Cover=({phase,onCovered,onGone,color})=>(
  <AnimatePresence>
    {phase!=='idle'&&(
      <motion.div
        className="liquid"
        style={{background:color}}
        initial={{y:'-100%'}}
        animate={phase==='covering'?{y:0}:{y:'100%'}}
        exit={{y:'100%'}}
        transition={coverT}
        onAnimationComplete={()=>{if(phase==='covering')onCovered?.();if(phase==='uncovering')onGone?.();}}
      >
        <div className="liquid-edge" style={{background:color}}/>
      </motion.div>
    )}
  </AnimatePresence>
);
function Cursor(){const mx=useMotionValue(-100),my=useMotionValue(-100);useEffect(()=>{const move=e=>{mx.set(e.clientX);my.set(e.clientY)};window.addEventListener('mousemove',move);return()=>window.removeEventListener('mousemove',move)},[mx,my]);return<motion.div aria-hidden className="cursor-dot" style={{x:mx,y:my}}/>}
function Home({toProjects}){const[locked,setLocked]=useState(false);useEffect(()=>{const wheel=e=>{if(!locked&&e.deltaY>45){setLocked(true);toProjects();}};window.addEventListener('wheel',wheel,{passive:true});return()=>window.removeEventListener('wheel',wheel);},[locked,toProjects]);const tags=[['设计与创新','#C2DF79','tag-a',-5],['AI 原生工作流','#FFF98B','tag-d',-7],['用户体验','#D2B4FF','tag-b',-4],['产品思维','#B1DCFF','tag-c',6]];return<main className="home"><section className="home-stage"><motion.h1 className="hero-title" initial={{y:-260}} animate={{y:0}} transition={{delay:.14,duration:.82,ease:dropEase}}>DESIGNER &<br/>CREATIVE DEVELOPER</motion.h1>{tags.map(([t,bg,cls,rot],i)=><motion.div key={t} className={`tag-cn ${cls}`} style={{backgroundColor:bg,rotate:`${rot}deg`}} initial={{y:-360}} animate={{y:0}} transition={{delay:.22+i*.1,duration:.84,ease:dropEase}}>{t}</motion.div>)}<motion.div className="home-meta" initial={{y:-120,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:.55,duration:.55,ease:'circOut'}}>用户界面设计,<br/>UI/UX DESIGN<br/>PRODUCT STRATEGY<br/>VIBE CODING<br/>AI-INTEGRATED</motion.div><motion.div className="scroll-tip" animate={{opacity:[.25,1,.25]}} transition={{repeat:Infinity,duration:1.8}}>SCROLL/向下滑动</motion.div></section></main>}
const Sidebar=({cat,open,close})=>{const list=projects.filter(p=>p.cat===cat?.id);return<AnimatePresence>{cat&&<motion.aside className="side" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{duration:.32,ease:[.22,1,.36,1]}}><button className="side-close" onClick={close}>×</button><h2>{cat.label}</h2>{list.map((p,i)=><button key={p.slug} onClick={()=>open(p)} className="side-card"><div className="thumb">{p.thumbSide?<img src={p.thumbSide} alt={p.title}/>:<span>{p.title}</span>}</div><p>{p.title}</p><small>{cat.label} / {String(i+1).padStart(2,'0')}</small></button>)}</motion.aside>}</AnimatePresence>};
function ProjectsDropIntro({runKey,onDone}){const doneRef=useRef(false);useEffect(()=>{doneRef.current=false},[runKey]);const bars=[{id:'green',color:'#68FF74'},{id:'pink',color:'#FF98EE'},{id:'yellow',color:'#F9FF52'},{id:'blue',color:'#7EDAFF'}];return<AnimatePresence>{!doneRef.current&&<motion.div key={runKey} className="projects-drop" initial={{opacity:1}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.12}}>{bars.map((b,i)=><motion.div key={b.id} className="projects-drop-bar" style={{background:b.color,top:`${i*25}vh`}} initial={{y:'-100vh'}} animate={{y:0}} transition={{duration:.18,ease:[.12,.9,.12,1],delay:i*.07}} onAnimationComplete={()=>{if(i===bars.length-1){doneRef.current=true;onDone?.();}}}/> )}</motion.div>}</AnimatePresence>}
function Projects({openDetail,introKey}){const[active,setActive]=useState(null);const[showIntro,setShowIntro]=useState(true);useEffect(()=>{setShowIntro(true);setActive(null)},[introKey]);return<main className="projects-page">{showIntro&&<ProjectsDropIntro runKey={introKey} onDone={()=>setShowIntro(false)}/>}<section className="projects-stage"><motion.p className="projects-tip" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.18}}>点击标签进入项目页 ▾</motion.p>{cats.map((c,i)=><motion.button key={c.id} className="cat-label" animate={{y:0,rotate:active===c.id?c.rot+3:c.rot}} style={{backgroundColor:c.color,left:`${c.x}%`,top:`${c.y}%`}} initial={{y:-320,rotate:c.rot}} transition={{delay:.12+i*.1,duration:.9,ease:dropEase}} whileHover={{scale:1.02}} whileTap={{scale:.98}} onClick={()=>setActive(c.id)}>{active===c.id&&<span className="play">▶</span>}{c.label}</motion.button>)}</section><Sidebar cat={cats.find(c=>c.id===active)} open={openDetail} close={()=>setActive(null)}/></main>}
function Detail({p,openDetail,back}){const[zoom,setZoom]=useState(1);const imgs=useMemo(()=>p.images.map(imgFor(p)),[p]);const current=order.indexOf(p.slug);const next=projects.find(x=>x.slug===order[(current+1)%order.length]);const otherCats=cats.filter(c=>c.id!==p.cat).map(c=>projects.find(x=>x.cat===c.id)).filter(Boolean);return<main className="detail"><button className="back" onClick={back}>‹ Back/返回</button><div className="zoom-fab"><button onClick={()=>setZoom(z=>Math.max(.85,+(z-.1).toFixed(2)))}>−</button><button onClick={()=>setZoom(z=>Math.min(1.2,+(z+.1).toFixed(2)))}>＋</button></div><header className="detail-wrap detail-head"><div><h1>{p.title}</h1><p>{p.tags}</p>{p.link&&<a className="detail-link" href={p.link} target="_blank" rel="noreferrer">Behance ↗</a>}</div><article><b>OVERVIEW / 项目概览</b><br/>{p.desc}</article></header><section className="detail-wrap image-flow" style={{zoom}}>{imgs.length?imgs.map(src=><img key={src} src={src} loading="lazy"/>):<div className="mock-big">{p.title}</div>}{p.reflection&&<div className="reflection"><h3>03. REFLECTION / 项目反思</h3><img src={p.reflection} alt="项目反思"/><p><b>Challenge:</b> {p.reflectionChallenge}</p><p><b>Outcome:</b> {p.reflectionOutcome}</p></div>}</section><section className="detail-wrap detail-bottom"><button className="next-link" onClick={()=>openDetail(next)}><span>Next/下一个项目 ›</span><strong>{next.title}</strong></button><div className="other-head">Other Categories/其他分类</div><div className="other-cats">{otherCats.map(item=><button key={item.slug} className="other-card" onClick={()=>openDetail(item)}><img src={item.thumbDetail} alt={item.title}/><div className="other-meta"><small>{catMap[item.cat].label}</small><span>{item.title}</span></div><div className="other-overlay" style={{backgroundColor:catMap[item.cat].color}}><b>Go To This Project</b><span>前往这个项目</span></div></button>)}</div></section></main>}
function About(){const a=aboutData;return<main className="about-page"><div className="about-grid"><div className="about-left"><div className="about-label about-introduction"><h3>INTRODUCTION<br/>/简介</h3></div><div className="about-label about-touch"><h3>GET IN TOUCH<br/>/联系方式</h3></div><div className="about-label about-workflow-label"><h3>AI-NATIVE WORKFLOW<br/>/ AI 原生工作流</h3></div><div className="about-label about-skills-label"><h3>SKILLS<br/>技能矩阵</h3></div><div className="about-label about-belief-label"><h3>WHAT CAN I DO IN THIS FAST CHANGING WORLD?<br/>/ 在这个瞬息万变的世界里，我能做些什么？</h3></div></div><div className="about-right"><section className="about-block about-top"><h2>{a.title}</h2>{a.intro.map(t=><p key={t} className="about-intro">{t}</p>)}<div className="pill-row about-chip-row">{a.chips.map(c=><span key={c} className="pill">{c}</span>)}</div></section><section className="about-block about-touch-block"><div className="pill-row"><a className="pill" href="https://www.behance.net/lylaliang2001" target="_blank" rel="noreferrer">Behance ↗</a><a className="pill" href="https://www.zcool.com.cn/u/24677441" target="_blank" rel="noreferrer">Zcool ↗</a><a className="pill" href="mailto:lylaliang01@gmail.com">Email ↗</a><span className="pill">Wechat</span></div></section><section className="about-block about-workflow">{a.steps.map(([n,t,d])=><div key={n} className="step"><span>{n}</span><div><b>{t}</b><p>{d}</p></div></div>)}</section><section className="about-block skills-list">{a.skills.map(s=><p key={s}>{s}</p>)}</section><section className="about-block belief"><h4>{a.beliefTitle}</h4>{a.belief.map((b,i)=><p key={i}>{b}</p>)}</section></div></div></main>}
export default function App(){const[route,setRoute]=useState('home');const[selected,setSelected]=useState(null);const[coverPhase,setCoverPhase]=useState('idle');const[target,setTarget]=useState(null);const[coverColor,setCoverColor]=useState(routeBg.home);const[introKey,setIntroKey]=useState(0);const go=(r,withCover=false)=>{if(!withCover){setSelected(null);setRoute(r);return;}setTarget(r);setCoverColor(routeBg[r]||routeBg.projects);setCoverPhase('covering');};const onCovered=()=>{if(!target)return;setSelected(null);setRoute(target);if(target==='projects')setIntroKey(k=>k+1);requestAnimationFrame(()=>setCoverPhase('uncovering'));};const onGone=()=>{setCoverPhase('idle');setTarget(null);};const openDetail=p=>{setSelected(p);setRoute('detail');window.scrollTo(0,0);};return<div className="app-shell"><style>{`body,button,a,*{cursor:none!important}`}</style><Cursor/>{route!=='detail'&&<Nav route={route} go={go}/>} {route==='home'&&<Home toProjects={()=>go('projects',true)}/>} {route==='projects'&&<Projects openDetail={openDetail} introKey={introKey}/>} {route==='detail'&&selected&&<Detail p={selected} openDetail={openDetail} back={()=>setRoute('projects')}/>} {route==='about'&&<About/>} <Cover phase={coverPhase} onCovered={onCovered} onGone={onGone} color={coverColor}/></div>}
