import { AnimatePresence, motion } from 'framer-motion';
import { useEffect, useMemo, useState } from 'react';
import { cats, projects, order, catMap, imgFor, aboutData } from './data.js';

const dropEase=[.34,1.56,.64,1];
const coverEase=[.83,0,.17,1];
const coverT={duration:.38,ease:coverEase};
const routeBg={home:'#FFFFFF',projects:'#307FFF',about:'#F6F5EE'};
const Nav=({route,go})=>
  <nav className={`nav ${route==='projects'?'nav-projects':route==='about'?'nav-about':''}`}>
    <button onClick={()=>go('home')}>HOME</button>
    <button onClick={()=>go('projects')}>PROJECTS</button>
    <button onClick={()=>go('about')}>ABOUT</button>
  </nav>;
const Cover=({phase,onCovered,onGone,color})=>(
  <AnimatePresence>
    {phase!=='idle'&&(
      <motion.div
        className="liquid"
        style={{background:color}}
        initial={{y:'-100%'}}
        animate={phase==='covering'?{y:0}:{y:'100%'}}
        exit={{y:'100%'}}
        transition={coverT}
        onAnimationComplete={()=>{if(phase==='covering')onCovered?.();if(phase==='uncovering')onGone?.();}}
      >
        <div className="liquid-edge" style={{background:color}}/>
      </motion.div>
    )}
  </AnimatePresence>
);
function Home({toProjects}){const[locked,setLocked]=useState(false);useEffect(()=>{const wheel=e=>{if(!locked&&e.deltaY>45){setLocked(true);toProjects();}};window.addEventListener('wheel',wheel,{passive:true});return()=>window.removeEventListener('wheel',wheel);},[locked,toProjects]);const tags=[['设计与创新','#C2DF79','tag-a',-5],['AI 原生工作流','#FFF98B','tag-d',-7],['用户体验','#D2B4FF','tag-b',-4],['产品思维','#B1DCFF','tag-c',6]];return<main className="home"><section className="home-stage"><motion.h1 className="hero-title" initial={{y:-260}} animate={{y:0}} transition={{delay:.14,duration:.82,ease:dropEase}}>DESIGNER &<br/>CREATIVE DEVELOPER</motion.h1>{tags.map(([t,bg,cls,rot],i)=><motion.div key={t} className={`tag-cn ${cls}`} style={{backgroundColor:bg,rotate:`${rot}deg`}} initial={{y:-360}} animate={{y:0}} transition={{delay:.22+i*.1,duration:.84,ease:dropEase}}>{t}</motion.div>)}<motion.div className="home-meta" initial={{y:-120,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:.55,duration:.55,ease:'circOut'}}>用户界面设计,<br/>UI/UX DESIGN<br/>PRODUCT STRATEGY<br/>VIBE CODING<br/>AI-INTEGRATED</motion.div><motion.div className="scroll-tip" animate={{opacity:[.25,1,.25]}} transition={{repeat:Infinity,duration:1.8}}>SCROLL/向下滑动</motion.div></section></main>}
const Sidebar=({cat,open,close})=>{const list=projects.filter(p=>p.cat===cat?.id);return<AnimatePresence>{cat&&<motion.aside className="side" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{duration:.32,ease:[.22,1,.36,1]}}><button className="side-close" onClick={close}>×</button><h2>{cat.label}</h2>{list.map((p,i)=><button key={p.slug} onClick={()=>open(p)} className="side-card"><div className="thumb">{p.thumbSide?<img src={p.thumbSide} alt={p.title}/>:<span>{p.title}</span>}</div><p>{p.title}</p><small>{cat.label} / {String(i+1).padStart(2,'0')}</small></button>)}</motion.aside>}</AnimatePresence>};
function ProjectsDropIntro({runKey,onDone}){useEffect(()=>{const timeout=window.setTimeout(()=>onDone?.(),280);return()=>window.clearTimeout(timeout)},[runKey,onDone]);return<div key={runKey} className="projects-drop" aria-hidden><div className="projects-drop-fill"/></div>}
function Projects({openDetail,introKey}){const[active,setActive]=useState(null);const[showIntro,setShowIntro]=useState(true);useEffect(()=>{setShowIntro(true);setActive(null)},[introKey]);const introDone=!showIntro;return<main className="projects-page">{showIntro&&<ProjectsDropIntro runKey={introKey} onDone={()=>setShowIntro(false)}/>}<section className={`projects-stage ${showIntro?'projects-stage-intro':''}`}><motion.p className="projects-tip" initial={false} animate={introDone?{opacity:1,y:0}:{opacity:0,y:12}} transition={{duration:.24,ease:'easeOut'}}>点击标签进入项目页 ▾</motion.p>{cats.map((c,i)=><motion.button key={c.id} className="cat-label" animate={introDone?{opacity:1,y:0,rotate:active===c.id?c.rot+3:c.rot}:{opacity:0,y:32,rotate:c.rot}} style={{backgroundColor:c.color,left:`${c.x}%`,top:`${c.y}%`}} initial={false} transition={{delay:introDone?i*.04:0,duration:.36,ease:[.22,1,.36,1]}} whileHover={introDone?{scale:1.02}:undefined} whileTap={introDone?{scale:.98}:undefined} onClick={()=>introDone&&setActive(c.id)}>{active===c.id&&<span className="play">▶</span>}{c.label}</motion.button>)}</section><Sidebar cat={cats.find(c=>c.id===active)} open={openDetail} close={()=>setActive(null)}/></main>}
function MediaAsset({src,title}){if(src.endsWith('.mp4')){return<video src={src} className="detail-media" autoPlay muted loop playsInline preload="metadata"/>}return<img src={src} loading="lazy" alt={title} className="detail-media"/>}
function Detail({p,openDetail,back}){const[zoom,setZoom]=useState(1);const imgs=useMemo(()=>p.images.map(imgFor(p)),[p]);const current=order.indexOf(p.slug);const next=projects.find(x=>x.slug===order[(current+1)%order.length]);const otherCats=cats.filter(c=>c.id!==p.cat).map(c=>projects.find(x=>x.cat===c.id)).filter(Boolean);return<main className="detail"><button className="back" onClick={back}>‹ Back/返回</button><div className="zoom-fab"><button onClick={()=>setZoom(z=>Math.max(.85,+(z-.1).toFixed(2)))}>−</button><button onClick={()=>setZoom(z=>Math.min(1.2,+(z+.1).toFixed(2)))}>＋</button></div><header className="detail-wrap detail-head"><div><h1>{p.title}</h1><p>{p.tags}</p>{p.link&&<a className="detail-link" href={p.link} target="_blank" rel="noreferrer">Behance ↗</a>}</div><article><b>OVERVIEW / 项目概览</b><br/>{p.desc}</article></header><section className="detail-wrap image-flow" style={{zoom}}>{imgs.length?imgs.map(src=><MediaAsset key={src} src={src} title={p.title}/>):<div className="mock-big">{p.title}</div>}{p.reflection&&<div className="reflection"><h3>03. REFLECTION / 项目反思</h3><img src={p.reflection} alt="项目反思"/><p><b>Challenge:</b> {p.reflectionChallenge}</p><p><b>Outcome:</b> {p.reflectionOutcome}</p></div>}</section><section className="detail-wrap detail-bottom"><button className="next-link" onClick={()=>openDetail(next)}><span>Next/下一个项目 ›</span><strong>{next.title}</strong></button><div className="other-head">Other Categories/其他分类</div><div className="other-cats">{otherCats.map(item=><button key={item.slug} className="other-card" onClick={()=>openDetail(item)}><img src={item.thumbDetail} alt={item.title}/><div className="other-meta"><small>{catMap[item.cat].label}</small><span>{item.title}</span></div><div className="other-overlay" style={{backgroundColor:catMap[item.cat].color}}><b>Go To This Project</b><span>前往这个项目</span></div></button>)}</div></section></main>}
function About(){const a=aboutData;const beliefHeadings=['核心定位：从“设计者”到“建造者”','技术态度：驾驭 AI 而非被替代','审美立场：数字原生与人类温度','终极行动：持续迭代，保持输出'];const beliefBodies=[a.belief[1],a.belief[3],a.belief[5],a.belief[7]];return<main className="about-page"><div className="about-shell"><div className="about-content"><section className="about-block about-intro-block"><h3 className="about-section-title">简介/INTRODUCTION</h3><h2 className="about-name">{a.title}</h2>{a.intro.map(t=><p key={t} className="about-intro">{t}</p>)}<div className="pill-row about-chip-row">{a.chips.map(c=><span key={c} className="pill">{c}</span>)}</div></section><section className="about-block"><h3 className="about-section-title">联系方式/GET IN TOUCH</h3><div className="pill-row about-contact-row"><a className="pill" href="https://www.behance.net/lylaliang2001" target="_blank" rel="noreferrer">Behance ↗</a><a className="pill" href="https://www.zcool.com.cn/u/24677441" target="_blank" rel="noreferrer">Zcool ↗</a><a className="pill" href="mailto:lylaliang01@gmail.com">Email ↗</a><span className="pill">Wechat</span></div></section><section className="about-block"><h3 className="about-section-title">AI 原生工作流/AI-NATIVE WORKFLOW</h3><div className="about-workflow">{a.steps.map(([n,t,d])=><div key={n} className="step"><span>{n}</span><div><b>{t}</b><p>{d}</p></div></div>)}</div></section><section className="about-block skills-list"><h3 className="about-section-title">技能矩阵/SKILLS</h3>{a.skills.map(s=><p key={s}>{s}</p>)}</section><section className="about-block belief"><h3 className="about-section-title">在这个瞬息万变的世界里，我能做些什么？/WHAT CAN I DO IN THIS FAST CHANGING WORLD?</h3><h4>{a.beliefTitle}</h4>{beliefHeadings.map((heading,index)=><div key={heading} className="belief-item"><p className="belief-heading">{heading}</p><p>{beliefBodies[index]}</p></div>)}</section></div><img className="about-signature" src="/assets/about/lyla.l.png" alt="Lyla Liang signature"/></div></main>}
export default function App(){const[route,setRoute]=useState('home');const[selected,setSelected]=useState(null);const[coverPhase,setCoverPhase]=useState('idle');const[target,setTarget]=useState(null);const[coverColor,setCoverColor]=useState(routeBg.home);const[introKey,setIntroKey]=useState(0);const go=(r,withCover=false)=>{if(r===route&&coverPhase==='idle')return;if(coverPhase!=='idle')return;if(!withCover){setSelected(null);setRoute(r);return;}setTarget(r);setCoverColor(routeBg[r]||routeBg.projects);setCoverPhase('covering');};const onCovered=()=>{if(!target)return;setSelected(null);setRoute(target);if(target==='projects')setIntroKey(k=>k+1);requestAnimationFrame(()=>setCoverPhase('uncovering'));};const onGone=()=>{setCoverPhase('idle');setTarget(null);};const openDetail=p=>{setSelected(p);setRoute('detail');window.scrollTo(0,0);};return<div className="app-shell">{route!=='detail'&&<Nav route={route} go={go}/>} {route==='home'&&<Home toProjects={()=>go('projects',true)}/>} {route==='projects'&&<Projects openDetail={openDetail} introKey={introKey}/>} {route==='detail'&&selected&&<Detail p={selected} openDetail={openDetail} back={()=>setRoute('projects')}/>} {route==='about'&&<About/>} <Cover phase={coverPhase} onCovered={onCovered} onGone={onGone} color={coverColor}/></div>}
